using Microsoft.OpenApi.Models;
using System.Reflection;

namespace Obscura.FinanceTracker.WebApi.Extensions
{
    public static class SwaggerExtensions
    {
        public static IServiceCollection AddSwaggerDocumentation(this IServiceCollection services)
        {
            services.AddEndpointsApiExplorer();
            services.AddSwaggerGen(options =>
            {
                // 1. Define API Metadata
                options.SwaggerDoc("v1", new OpenApiInfo
                {
                    Title = "Obscura Finance Tracker API",
                    Version = "v1",
                    Description = "Enterprise-grade API documentation for Obscura Finance Tracker."
                });

                // 2. Locate the XML file generated by the compiler
                var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
                var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);

                // 3. Include the XML comments in Swagger
                // includeControllerXmlComments: true ensures Controller-level <summary> are also read
                if (File.Exists(xmlPath))
                {
                    options.IncludeXmlComments(xmlPath, includeControllerXmlComments: true);
                }
            });

            return services;
        }

        // Swagger is only enabled in Development to avoid exposing API documentation
        // in staging or production environments.
        public static WebApplication UseSwaggerDocumentation(this WebApplication app)
        {
            if (app.Environment.IsDevelopment())
            {
                app.UseSwagger();
                app.UseSwaggerUI(options =>
                {
                    options.SwaggerEndpoint("/swagger/v1/swagger.json", "Obscura Finance Tracker API v1");

                    // Optional: Set Swagger UI to open at the application's root URL (e.g., localhost:port/)
                    // options.RoutePrefix = string.Empty; 
                });
            }

            return app;
        }
    }
}
